apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pvc
  namespace: awasome-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd # Change according to your cluster
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: awasome-api
data:
  local.ini: |
    [couchdb]
    single_node=true
    
    [chttpd]
    require_valid_user = true
    
    [httpd]
    WWW-Authenticate = Basic realm="administrator"
    
    [couch_peruser]
    enable = true
    
    [replicator]
    interval = 10
    retries_per_request = 2
    socket_options = [{keepalive, true}, {nodelay, false}]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
  namespace: awasome-api
  labels:
    app: couchdb
spec:
  serviceName: couchdb-headless
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3.3
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: awasome-api-secret
              key: COUCHDB_USERNAME
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: awasome-api-secret
              key: COUCHDB_PASSWORD
        ports:
        - containerPort: 5984
          name: couchdb
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
        - name: couchdb-config
          mountPath: /opt/couchdb/etc/local.d/local.ini
          subPath: local.ini
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /_up
            port: 5984
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /_up
            port: 5984
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
        securityContext:
          runAsUser: 5984
          runAsGroup: 5984
      volumes:
      - name: couchdb-config
        configMap:
          name: couchdb-config
  volumeClaimTemplates:
  - metadata:
      name: couchdb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: fast-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
  namespace: awasome-api
  labels:
    app: couchdb
spec:
  selector:
    app: couchdb
  ports:
  - name: couchdb
    port: 5984
    targetPort: 5984
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-headless
  namespace: awasome-api
  labels:
    app: couchdb
spec:
  clusterIP: None
  selector:
    app: couchdb
  ports:
  - name: couchdb
    port: 5984
    targetPort: 5984